### ISSUE TITLE
Demo Link Not Working and Fetch Error in Console

### ISSUE THREAD

**Issue by hawav** [tomgroenwoldt/helix-editor-playground#4]
The demo link provided in the description of the Helix Editor Playground is not loading properly. Upon opening the link, the busy indicator continues to spin without loading any content. Additionally, opening the developer tools reveals errors in the console.

Steps to Reproduce:

Navigate to the following URL: https://tomgroenwoldt.github.io/helix-editor-playground/
Observe the busy indicator spinning indefinitely.
Open the browser's developer tools and inspect the console.

Note the error messages:

```
GET https://helix-editor-playground.keygli.de/versions net::ERR_CONNECTION_CLOSED
   (anonymous) @ App.tsx:26
   il @ react-dom.production.min.js:244
   kc @ react-dom.production.min.js:286
   (anonymous) @ react-dom.production.min.js:282
   C @ scheduler.production.min.js:13
   T @ scheduler.production.min.js:14
   App.tsx:26 
        
Uncaught (in promise) TypeError: Failed to fetch
   at App.tsx:26:5
   at il (react-dom.production.min.js:244:332)
   at kc (react-dom.production.min.js:286:111)
   at react-dom.production.min.js:282:391
   at C (scheduler.production.min.js:13:203)
   at MessagePort.T (scheduler.production.min.js:14:128)
```

**Comment by tomgroenwoldt** [comment]
Hey, this demo is not hosted anymore. GitHub actions still build the backend though. So if you want to experiment with this, you can host your backend yourself with the [built docker image](https://github.com/tomgroenwoldt/helix-editor-playground/pkgs/container/helix-editor-playground-backend).

**Comment by tomgroenwoldt** [comment]
I've adjusted the `README` for a local setup :) If you have any questions about this feel free to ask in another issue.
